version: '3'
services:

  sandbox:
    image: ja7adr/golang-playground:sandbox-1.24.0
    restart: always
    command: -mode=server -listen=0.0.0.0:80 -workers=1 -untrusted-container=ja7adr/golang-playground:actuator-1.24.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - playground
    depends_on:
      - memcached

  web:
    image: ja7adr/golang-playground:web-1.24.0
    restart: always
    environment:
      - SANDBOX_BACKEND_URL=http://sandbox:/run
      - MEMCACHED_ADDR=memcached:11211
    ports:
      - 9023:8080
    depends_on:
      - sandbox
    networks:
      - playground

  memcached:
    image: memcached:1.6.15-alpine
    command: memcached -m 64
    networks:
      - playground
networks:
  playground: